@url = http://localhost:8080/baby

###
### Find
GET {{url}}/1 HTTP/1.1
Accept: application/json

###

### Create
POST {url}}/create
Content-Type: application/json

{
  "name" : "Baby",
  "gender" : "girl",
  "birth_date" : "20250619",
  "user_id" : 1
}

###

### Update
PUT {url}}/edit/1
Content-Type: application/json

{
  "name" : "Updated Baby"
}

###

### Delete by id
GET {{url}}/delete/1
Accept: application/json
