@url = http://localhost:8080/journal

###
### Find
GET {{url}}/1 HTTP/1.1
Accept: application/json

###

### Create
POST {url}}/create
Content-Type: application/json

{
  "user_id" : 1,
  "text" : "took first steps. today was rough",
  "timestamp" : "20250619"
}

###

### Update
PUT {url}}/edit/1
Content-Type: application/json

{
  "text" : "Updated Journal"
}

###

### Delete by id
GET {{url}}/delete/1
Accept: application/json
